export const GuardianReasonCodes = {
  PASS: "GUARDIAN_PASS",
  PHASE3_OBSERVED: "GUARDIAN_PHASE3_OBSERVED",
  VALIDATOR_ERROR_OBSERVED: "GUARDIAN_VALIDATOR_ERROR_OBSERVED",
  CONFIG_UNAVAILABLE_OBSERVED: "GUARDIAN_CONFIG_UNAVAILABLE_OBSERVED",
  G12_STRUCTURED_OUTPUT_PASS: "G12_STRUCTURED_OUTPUT_PASS",
  G12_STRUCTURED_OUTPUT_OBSERVED: "G12_STRUCTURED_OUTPUT_OBSERVED",
  G13_PLACEHOLDER_LEAK_OBSERVED: "G13_PLACEHOLDER_LEAK_OBSERVED",
  G14_INTERNAL_LEAK_OBSERVED: "G14_INTERNAL_LEAK_OBSERVED",
  G15_PROMPT_INJECTION_OBSERVED: "G15_PROMPT_INJECTION_OBSERVED",
  G16_SCOPE_RISK_OBSERVED: "G16_SCOPE_RISK_OBSERVED",
  G17_NATURALNESS_RISK_OBSERVED: "G17_NATURALNESS_RISK_OBSERVED",
  G23_OBSERVABILITY_LOGGED: "G23_OBSERVABILITY_LOGGED",
} as const;
