import pino from 'pino';
import { env } from '../config/env.js';

const isDev = env.NODE_ENV === 'development';

export const logger = pino({
  level: isDev ? 'debug' : 'info',
  transport: isDev
    ? {
        target: 'pino-pretty',
        options: {
          colorize: true,
          translateTime: 'HH:MM:ss Z',
          ignore: 'pid,hostname',
        },
      }
    : undefined,
  redact: {
    paths: [
      'req.headers.authorization',
      'req.headers.Authorization',
      'req.headers.cookie',
      'req.headers.Cookie',
      'req.headers["x-tenant-id"]',
      'req.headers["x-api-key"]',
      'req.headers["api-key"]',
      'req.headers.apikey',
      'password',
      'pass',
      'senha',
      'token',
      'accessToken',
      'refreshToken',
      'oldRefreshToken',
      'secret',
      'apiKey',
      'api_key',
      'authorization',
      'cookie',
      'signature',
      'whatsapp',
      'phone',
      'telephone',
      'number',
      'email',
      'rawBody',
      'body',
      'payload',
      'messageContent',
      'content',
      'text',
      '*.password',
      '*.pass',
      '*.senha',
      '*.token',
      '*.accessToken',
      '*.refreshToken',
      '*.oldRefreshToken',
      '*.secret',
      '*.apiKey',
      '*.api_key',
      '*.authorization',
      '*.cookie',
      '*.signature',
      '*.whatsapp',
      '*.phone',
      '*.number',
      '*.telephone',
      '*.email',
      '*.rawBody',
      '*.body',
      '*.payload',
      '*.messageContent',
      '*.content',
      '*.text',
      'req.body.whatsapp',
      'req.body.phone',
      'req.body.number',
      'req.body.email',
      'req.body.password',
      'req.body.token',
      'req.body.accessToken',
      'req.body.refreshToken'
    ],
    censor: '*** [PII REDACTED]',
  },
});
